# Generated by Django 2.2.6 on 2019-10-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('numero_serie', models.IntegerField(verbose_name='Numero de Serie')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
            ],
        ),
    ]
