# Generated by Django 2.2.6 on 2019-10-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador_servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=20)),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='modelo',
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=30)),
                ('dt_saida', models.DateField(verbose_name='Data de Saida')),
                ('dt_retorno', models.DateField(verbose_name='Data de Retorno')),
                ('descricao', models.TextField(max_length=200)),
                ('servico_executado', models.CharField(max_length=50)),
                ('resposavel_interno', models.CharField(max_length=50)),
                ('resposavel_empresa', models.CharField(max_length=50)),
                ('valor_servico', models.IntegerField()),
                ('ns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonial.Equipamento')),
            ],
        ),
    ]
