# Generated by Django 2.2.6 on 2019-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0002_auto_20191025_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.ManyToManyField(to='patrimonial.Marca'),
        ),
    ]
