# Generated by Django 2.2.6 on 2019-10-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0003_equipamento_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='marca',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonial.Marca'),
            preserve_default=False,
        ),
    ]
