# Generated by Django 2.2.6 on 2019-10-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0004_auto_20191025_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonial.Modelo'),
            preserve_default=False,
        ),
    ]
