# Generated by Django 2.2.6 on 2019-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0005_equipamento_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(max_length=30, verbose_name='Numero de Serie'),
        ),
    ]
