# Generated by Django 2.2.6 on 2019-10-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0006_auto_20191025_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonial.Prestador_servico'),
            preserve_default=False,
        ),
    ]
