# Generated by Django 2.2.6 on 2019-10-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonial', '0007_os_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='dt_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Retorno'),
        ),
    ]
